src/SimpleMusicStore.Web/Models/ViewModels/RecordViewModel.cs
using SimpleMusicStore.Web.Models.Dtos;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleMusicStore.Web.Models.ViewModels
{
    public class RecordViewModel
    {
        [Required]
        public int Id { get; set; }

        public string Title { get; set; }

        public string ImageUrl { get; set; }

        public string Description { get; set; }

        public string Genre { get; set; }

        public int Year { get; set; }

        public List<VideoDto> Videos { get; set; }

        public List<TrackDto> Tracks { get; set; }

        public ArtistDto Artist { get; set; }

        public LabelDto Label { get; set; }

        public List<CommentDto> Comments { get; set; }

        [Required]
        public string Comment { get; set; }

        public decimal Price { get; set; }

        public bool IsFollowed { get; set; } = false;

        public string Format { get; set; }

        public bool IsActive { get; set; }
    }
}

src/SimpleMusicStore.Web/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimpleMusicStore.Data;
using SimpleMusicStore.Web.Models.ViewModels;
using SimpleMusicStore.Web.Services;

namespace SimpleMusicStore.Web.Controllers
{
    public class ArtistsController : Controller
    {
        private readonly ArtistService _artistService;
        private readonly IMapper _mapper;

        

        public ArtistsController(SimpleMusicStoreContext context, IMapper mapper)
        {
            _artistService = new ArtistService(context);
            _mapper = mapper;
        }



        //public async Task<IActionResult> All(string sort = "")
        //{
        //    var userId = "";
        //    if (User != null)
        //    {
        //        userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        //    }
        //    var model = (await _artistService.AllAsync(sort, userId)).Select(_mapper.Map<ArtistViewModel>).ToList();
        //
        //    return View(model);
        //}

        public async Task<IActionResult> Details(int artistId)
        {
            var artist = await _artistService.GetAsync(artistId);

            if (artist is null)
            {
                return Redirect("/");
            }

            var model = _mapper.Map<ArtistViewModel>(artist);

            if (User.Identity.IsAuthenticated)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (artist.Followers.Any(lu => lu.UserId == userId))
                {
                    model.IsFollowed = true;
                }
                model.Comments.ForEach(c => c.IsCreator = c.UserId == userId);
            }

            model.Records = model.Records.Where(r=>r.IsActive).OrderByDescending(r => r.DateAdded).ToList();
            model.Comments = model.Comments.OrderByDescending(c => c.DatePosted).ToList();

            return View(model);
        }



        [Authorize]
        public async Task<IActionResult> Follow(int artistId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _artistService.FollowAsync(artistId, userId);

            return Redirect(Request.Headers["Referer"].ToString());
        }


        [Authorize]
        public async Task<IActionResult> Unfollow(int artistId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _artistService.UnfollowAsync(artistId, userId);
        
            return Redirect(Request.Headers["Referer"].ToString());
        }

    }
}

src/SimpleMusicStore.Web/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SimpleMusicStore.Data;
using SimpleMusicStore.Data.Models;
using SimpleMusicStore.Web.Models.ViewModels;
using SimpleMusicStore.Web.Services;

namespace SimpleMusicStore.Web.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {
        private CommentService _commentService;
        
        

        public CommentsController(SimpleMusicStoreContext context)
        {
            _commentService = new CommentService(context);
        }
        


        [HttpPost]
        public async Task<IActionResult> CommentRecord(int recordId, RecordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Redirect(Request.Headers["Referer"].ToString());
            }
            
            await _commentService.AddAsync<Record>(recordId, model.Comment, GetUserId);

            return Redirect($"/records/details?recordId={recordId}");
        }



        [HttpPost]
        public async Task<IActionResult> CommentArtist(int artistId, ArtistViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Redirect($"/artists/details?artistId={artistId}");
            }

            await _commentService.AddAsync<Artist>(artistId, model.Comment, GetUserId);

            return Redirect($"/artists/details?artistId={artistId}");
        }

        [HttpPost]
        public async Task<IActionResult> CommentLabel(int labelId, LabelViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Redirect($"/labels/details?labelId={labelId}");
            }
            
            await _commentService.AddAsync<Label>(labelId, model.Comment, GetUserId);

            return Redirect($"/labels/details?labelId={labelId}");
        }

        public async Task<IActionResult> Remove(int commentId)
        {
            await _commentService.RemoveAsync(commentId, GetUserId);

            return Redirect(Request.Headers["Referer"].ToString());
        }

        private string GetUserId => User.FindFirstValue(ClaimTypes.NameIdentifier);
    }
}

src/SimpleMusicStore.Web/Controllers/LabelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimpleMusicStore.Data;
using SimpleMusicStore.Web.Models.ViewModels;
using SimpleMusicStore.Web.Services;

namespace SimpleMusicStore.Web.Controllers
{
    public class LabelsController : Controller
    {
        private readonly LabelService _labelService;
        private readonly IMapper _mapper;



        public LabelsController(SimpleMusicStoreContext context, IMapper mapper)
        {
            _labelService = new LabelService(context);
            _mapper = mapper;
        }



        //public async Task<IActionResult> All(string orderBy = "")
        //{
        //    var userId = "";
        //    if (User != null)
        //    {
        //        userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        //    }
        //
        //    var model = (await _labelService.AllAsync(orderBy, userId)).Select(_mapper.Map<LabelViewModel>).ToList();
        //
        //    return View(model);
        //}

        public async Task<IActionResult> Details(int labelId)
        {
            var label = await _labelService.GetAsync(labelId);

            if (label is null)
            {
                return Redirect("/");
            }

            var model = _mapper.Map<LabelViewModel>(label);

            if (User.Identity.IsAuthenticated)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (label.Followers.Any(lu => lu.UserId == userId))
                {
                    model.IsFollowed = true;
                }
                model.Comments.ForEach(c => c.IsCreator = c.UserId == userId);
            }

            model.Records = model.Records.Where(r=>r.IsActive).OrderByDescending(r => r.DateAdded).ToList();
            model.Comments = model.Comments.OrderByDescending(c => c.DatePosted).ToList();

            return View(model);
        }


        [Authorize]
        public async Task<IActionResult> Follow(int labelId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _labelService.FollowAsync(labelId, userId);

            return Redirect(Request.Headers["Referer"].ToString());
        }



        [Authorize]
        public async Task<IActionResult> Unfollow(int labelId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _labelService.UnfollowAsync(labelId, userId);

            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

src/SimpleMusicStore.Web/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimpleMusicStore.Data;
using SimpleMusicStore.Web.Models.Dtos;
using SimpleMusicStore.Web.Models.ViewModels;
using SimpleMusicStore.Web.Services;

namespace SimpleMusicStore.Web.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly OrderService _orderService;
        private readonly RecordService _recordService;
        private readonly AddressService _addressService;
        private readonly IMapper _mapper;




        public OrdersController(SimpleMusicStoreContext context, IMapper mapper)
        {
            _orderService = new OrderService(context, mapper);
            _recordService = new RecordService(context);
            _addressService = new AddressService(context);
            _mapper = mapper;
        }



        public async Task<IActionResult> Details(int orderId)
        {
            var order = await _orderService.GetAsync(orderId);

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (order == null || order.UserId != userId)
            {
                return Redirect("/profile/orders");
            }

            var model = _mapper.Map<CartOrderViewModel>(order);

            return View(model);
        }



        public IActionResult Cart()
        {
            var model = GetCart();

            return View(model);
        }


        public async Task<IActionResult> Preview(string sessionId)
        {
            if (sessionId != HttpContext.Session.Id)
            {
                return RedirectToAction("Cart");
            }

            var model = GetCart();
            
            if (model.Items.Count() == 0)
            {
                return RedirectToAction("Cart");
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            model.Addresses = (await _addressService.AllByUserAsync(userId)).Select(_mapper.Map<AddressDto>).ToList();

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Preview(string sessionId, CartOrderViewModel model)
        {
            if (sessionId != HttpContext.Session.Id)
            {
                return RedirectToAction("Cart");
            }

            var cart = GetCart();

            if (cart.Items.Count() == 0)
            {
                return RedirectToAction("Cart");
            }

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Please select delivery address!");

                return View(cart);
            }


            
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var orderId = await _orderService.OrderAsync(model, userId, HttpContext.Session, cart.TotalPrice());

            return Redirect($"/orders/details?orderId={orderId}");
        }
        


        public IActionResult AddToCart(int recordId)
        {
            _orderService.AddToCart(recordId, HttpContext.Session);

            return RedirectToAction("Cart");
        }



        public IActionResult RemoveFromCart(int recordId)
        {
            _orderService.RemoveFromCart(recordId, HttpContext.Session);

            return RedirectToAction("Cart");
        }


        public IActionResult DecreaseQuantity(int recordId)
        {
            _orderService.DecreaseQuantity(recordId, HttpContext.Session);

            return RedirectToAction("Cart");
        }



        //public IActionResult EmptyCart(int recordId)
        //{
        //    _orderService.EmptyCart(HttpContext.Session);
        //
        //    return RedirectToAction("Cart");
        //}




        private CartOrderViewModel GetCart()
        {
            var items = new List<CartRecordViewModel>();
            var cart = _orderService.GetCart(HttpContext.Session);
            if (cart != null)
            {
                items = _orderService.GetCart(HttpContext.Session)
                    .Select(c =>
                    {
                        var record = _recordService.Get(c.RecordId);
                        var cartRecordViewModel = _mapper.Map<CartRecordViewModel>(record);
                        cartRecordViewModel.Quantity = c.Quantity;
                        return cartRecordViewModel;
                    })
                    .ToList();
            }

            return new CartOrderViewModel { Items =  items, SessionId = HttpContext.Session.Id };
        }
    }
}

src/SimpleMusicStore.Web/Controllers/RecordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SimpleMusicStore.Data;
using SimpleMusicStore.Data.Models;
using SimpleMusicStore.Web.Models.ViewModels;
using SimpleMusicStore.Web.Services;

namespace SimpleMusicStore.Web.Controllers
{
    public class RecordsController : Controller
    {
        private readonly RecordService _recordService;
        private readonly IMapper _mapper;
        private readonly UserManager<SimpleUser> _userManager;





        public RecordsController(SimpleMusicStoreContext context, IMapper mapper, UserManager<SimpleUser> userManager)
        {
            _recordService = new RecordService(context);
            _mapper = mapper;
            _userManager = userManager;
        }



        public async Task<IActionResult> All(string sort = "newest", List<string> selectedGenres = null, List<string> selectedFormats = null, string search = "")
        {
            var userId = "";
            if (User != null)
            {
                userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            }
            var records = (await _recordService.AllAsync(sort, userId, selectedGenres, selectedFormats, search)).Select(_mapper.Map<RecordViewModel>).ToList();
            var model = new AllRecordsViewModel
            {
                Records = records,
                Sort = sort,
                AllGenres = _recordService.GetAllGenres(),
                SelectedGenres = selectedGenres,
                AllFormats = _recordService.GetAllFormats(),
                SelectedFormats = selectedFormats,
                Search = search
            };

            return View(model);
        }




        public async Task<IActionResult> Details(int recordId)
        {
            var record = await _recordService.GetAsync(recordId);

            if (record is null)
            {
                return RedirectToAction("All");
            }

            var model = _mapper.Map<RecordViewModel>(record);

            if (User.Identity.IsAuthenticated)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                if (record.WantedBy.Any(ru=> ru.UserId == userId))
                {
                    model.IsFollowed = true;
                }

                model.Comments.ForEach(c => c.IsCreator = c.UserId == userId);
            }

            model.Comments = model.Comments.OrderByDescending(c => c.DatePosted).ToList();

            return View(model);


        }



        [Authorize]
        public async Task<IActionResult> AddToWantlist(int recordId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _recordService.AddToWantlistAsync(recordId, userId);;
            return Redirect(Request.Headers["Referer"].ToString());
        }



        [Authorize]
        public async Task<IActionResult> RemoveFromWantList(int recordId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _recordService.RemoveFromWantlistAsync(recordId, userId);
            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

src/SimpleMusicStore.Web/Views/Records/All.cshtml
@model  SimpleMusicStore.Web.Models.ViewModels.AllRecordsViewModel
@{
    ViewData["Title"] = "All Records";
}
<br />
<h2>All Records</h2>
<hr />
<br />
<div class="row">
    <div class="col-md-2">
        <form method="get">
            <div class="form-group">
                <p><strong>Search</strong></p>
                <input asp-for="Search" name="search" class="form-control" />
            </div>
            <hr />
            <div class="form-group">
                <p><strong>Sort By</strong></p>
                <div class="radio">
                    <label><input asp-for="Sort" name="sort" type="radio" value="newest">Date added</label>
                </div>
                <div class="radio">
                    <label><input asp-for="Sort" name="sort" type="radio" value="alphabetically">Alphabetically</label>
                </div>
                <div class="radio">
                    <label><input asp-for="Sort" name="sort" type="radio" value="popularity">Popularity</label>
                </div>
                <div class="radio">
                    <label><input asp-for="Sort" name="sort" type="radio" value="recommended">Recommended</label>
                </div>
            </div>
            <hr />
            <div class="form-group">
                <p><strong>Genres</strong></p>
                @for (int i = 0; i < Model.AllGenres.Count; i++)
                {
                    var genre = Model.AllGenres[i];
                    <div class="checkbox">
                        <label><input  name="selectedGenres" type="checkbox" value="@genre"
                                       @if(Model.SelectedGenres.Any(g=>g == genre))
                                     {
                                         @:checked
                                     }
                                      />@genre</label>
                    </div>
                }
            </div>
            <hr />
            <div class="form-group">
                <p><strong>Formats</strong></p>
                @for (int i = 0; i < Model.AllFormats.Count; i++)
                {
                    var format = Model.AllFormats[i];
                    <div class="checkbox">
                        <label><input name="selectedFormats" type="checkbox" value="@format"
                                     @if(Model.SelectedFormats.Any(f=>f == format))
                                     {
                                         @:checked
                                     }
                                      >@format</label>
                    </div>
                }
            </div>
            <hr />
            <div class="form-group"><button type="submit" class="btn btn-default">Sort</button></div>
        </form>
    </div>
    
    
    <div class="col-md-10">
        <div class="row">
            @for (int i = 0; i < Model.Records.Count; i++)
            {
                if (i % 5 == 0)
                {

                @:</div>
                @:<div class="row">
                    <br />
                }

                var record = Model.Records[i];

                <div class="col-md-2">
                    <div class="form-group">
                        <a asp-controller="Records" asp-action="Details" asp-route-recordId="@record.Id">
                            <img src="@record.ImageUrl" alt="@record.Artist  - @record.Title" width="100%" height="100%" />
                        </a>
                    </div>
                    <div>
                        <a asp-controller="Artists" asp-action="Details" asp-route-artistId="@record.Artist.Id">
                            @record.Artist.Name
                        </a> –
                    </div>
                    <div>
                        <a asp-controller="Records" asp-action="Details" asp-route-recordId="@record.Id">
                            @record.Title
                        </a>
                    </div>
                    <div>
                        <a asp-controller="Labels" asp-action="Details" asp-route-labelId="@record.Label.Id">
                            [@record.Label.Name]
                        </a>
                    </div>
                </div>
            }
        </div>

    </div>
</div>

src/SimpleMusicStore.Web/Views/Records/Details.cshtml
@model SimpleMusicStore.Web.Models.ViewModels.RecordViewModel
@{
    ViewData["Title"] = Model.Artist.Name + " - " + Model.Title;
}
    <br />
    <div class="row">
        <div class="col-md-3">
            <img src="@Model.ImageUrl" alt="" height="100%" width="100%" />
        </div>
        <div class="col-md-9">
            <h3><strong>@Model.Title</strong></h3>
            <hr />
            <div class="col-md-5">

                <table>
                    <col width="80" />
                    <col width="300" />
                    <tr>
                        <td><h4><strong>Artist:</strong></h4></td>
                        <td><a asp-area="" asp-controller="Artists" asp-action="Details" asp-route-artistId="@Model.Artist.Id"><h4>@Model.Artist.Name</h4></a></td>
                    </tr>
                    <tr>
                        <td><h4><strong>Label:</strong></h4></td>
                        <td><a asp-area="" asp-controller="Labels" asp-action="Details" asp-route-labelId="@Model.Label.Id"><h4>@Model.Label.Name</h4></a></td>
                    </tr>
                    <tr>
                        <td><h4><strong>Year:</strong></h4></td>
                        <td><h4>@Model.Year</h4></td>
                    </tr>
                    <tr>
                        <td><h4><strong>Genre:</strong></h4></td>
                        <td><h4>@Model.Genre</h4></td>
                    </tr>
                    <tr>
                        <td><h4><strong>Format:</strong></h4></td>
                        <td><h4>@Model.Format</h4></td>
                    </tr>
                </table>
            </div>



            <div class="col-md-7">
                <h3><strong>Price: </strong>$@Model.Price</h3>
                <div class="row">
                    <div class="col-md-5">
                        <div class="form-group">
                            @if (Model.IsActive)
                            {
                                <a asp-area="" asp-controller="Orders" asp-action="AddToCart" asp-route-recordId="@Model.Id"><button type="submit" class="btn btn-group btn-default"><span class="glyphicon glyphicon-shopping-cart"></span> Buy</button></a>
                            }

                        </div>
                        <div class="form-group">
                            @if (Model.IsFollowed)
                            {
                                <a asp-area="" asp-controller="Records" asp-action="RemoveFromWantlist" asp-route-recordId="@Model.Id"><button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-heart"></span> Remove from Wantlist</button></a>

                            }
                            else
                            {
                                <a asp-area="" asp-controller="Records" asp-action="AddToWantlist" asp-route-recordId="@Model.Id"><button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-heart-empty"></span> Add to Wantlist</button></a>
                            }
                        </div>
                    </div>
                    <div class="col-md-3">
                        @if (User.IsInRole("Admin"))
                        {
                            <div class="form-group">
                                <a asp-area="Admin" asp-controller="Record" asp-action="Edit" asp-route-recordId="@Model.Id"><button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit</button></a>
                            </div>
                            <div class="form-group">
                                <a asp-area="Admin" asp-controller="Record" asp-action="Remove" asp-route-recordId="@Model.Id"><button type="submit" class="btn btn-default" onclick="return confirm('Are you sure you want to remove this record from the store?');"><span class="glyphicon glyphicon-remove"></span> Remove</button></a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <hr />
    <div class="row">
        <div class="col-md-6">
            <h4><strong><span class="glyphicon glyphicon-list"></span> Tracklist</strong></h4>
            <hr />
            <table>
                <col width="30" />
                <col width="485" />
                <col width="40" />

                @for (int i = 0; i < Model.Tracks.Count; i++)
                {
                    var track = Model.Tracks[i];
                    <tr>
                        <td>@(i + 1).</td>
                        <td>@track.Title</td>
                        <td>@track.Duration</td>
                    </tr>
                }
            </table>
            <br />
            <hr />
            <h4><strong><span class="glyphicon glyphicon-comment"></span> Comments</strong></h4>
            <hr />
            <form asp-controller="Comments" asp-action="CommentRecord" asp-route-recordId="@Model.Id" method="post">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <textarea asp-for="Comment" class="form-control" rows="4"></textarea>
                            <span asp-validation-for="Comment" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> Comment</button>
                </div>
            </form>
            <div class="row">
                <div class="col-md-12">
                    @foreach (var comment in Model.Comments)
                    {
                        <hr />
                        <div class="form-group">
                            <span class="glyphicon glyphicon-user"></span><strong> @comment.User</strong>&nbsp;&nbsp;&nbsp;&nbsp;
                            <small><span class="glyphicon glyphicon-time"></span> @comment.DateFormat</small>
                        </div>
                        <div class="form-group" style="word-wrap : break-word">@comment.Content</div>
                        if (comment.IsCreator)
                        {
                            <a asp-controller="Comments" asp-action="Remove" asp-route-commentId="@comment.Id"><button type="submit" class="btn btngroup btn-default" onclick="return confirm('Are you sure you want to remove this comment?');"><span class="glyphicon glyphicon-remove"></span> Remove</button></a>
                        }
                    }
                </div>
            </div>
            <br />
            <hr />
        </div>

            <div class="col-md-6">
                <h4><strong><span class="glyphicon glyphicon-film"></span> Videos</strong></h4>
                <hr />
                @foreach (var video in Model.Videos)
                {
                    <iframe width="250" height="180" src="https://www.youtube.com/embed/@video.YoutubeId"></iframe>
                }
            </div>
    </div>